### PR TITLE
git tasks

### PR DESCRIPTION
**Pull request by hristiyan098**

### CODE REVIEW

**Comment by mgenov** [comment]
Please rebase your working branch with upstream as there are conflicts.

**Comment by hristiyan098** [comment]
> Please rebase your working branch with upstream as there are conflicts.

Done.

**Review by mgenov — APPROVED** [review]
LGTM!

**Comment by mgenov** [comment]
You can move with Go Intro tasks. There is a repo created for this task: https://github.com/clouway-incubator/hristiyan-go-intro

**Pull request merged**
